services:
  api:
    container_name: rental_cars
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4652:8080"
    networks:
      - rental_cars_network
    depends_on:
      postgres:
        condition: service_healthy  
      rabbitmq:
        condition: service_healthy 

  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234@Teste
      POSTGRES_DB: rentalcars_db
    volumes:
      - c:\dados\volumes\postgres:/var/lib/postgresql/data
    networks:
      rental_cars_network:
        aliases:
          - "postgres-db"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rental_cars_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - rental_cars_network

networks:
  rental_cars_network:
    driver: bridge
